### ISSUE TITLE
Add one more argument to motivation

### ISSUE THREAD

**Issue by bkamins** [jkrumbiegel/Chain.jl#12]
When you use Pipe.jl there is a small problem that `Pipe` is a name defined and exported in Julia Base. Maybe also this could be mentioned in the list of motivations?

**Comment by jkrumbiegel** [comment]
Though I never encountered this particular problem I'll include it, thanks! :)

**Comment by bkamins** [comment]
Sure - the biggest issue for most users is probably that `Pipe` is highlighted in the editor in a different way because of this 😄:
![image](https://user-images.githubusercontent.com/6187170/104169145-64edbd00-53ff-11eb-8709-c6ce1d1f08f9.png)

**Comment by waldyrious** [comment]
For future reference, this was addressed in commit df8951ec76a051bbfcd13041f1a035ac2ad05075.
