### ISSUE TITLE
Empty chain returns nothing

### ISSUE THREAD

**Issue by jtrakk** [jkrumbiegel/Chain.jl#16]
```julia
julia> @chain 1 begin; end

julia> 
```

I was expecting it to return the argument, in this case, 1.

---
[8be319e6] Chain v0.4.3

**Comment by stillyslalom** [comment]
This behaves no different from base Julia:
```
julia> x₁ = begin; end

julia> isnothing(x₁)
true
```
If you want to return the argument, use an underscore:
```
julia> x₂ = @chain 1 begin; _; end
1
```

**Comment by jkrumbiegel** [comment]
I wonder in what context this came up? The logic is that in the chain, every expression has a replacement logic applied to it and its result forwarded. If there's no expression, then I would think, as @stillyslalom says, it is sensible that `nothing` is returned.

**Comment by jtrakk** [comment]
The way I think of it is that `@chain` takes a sequence of functions that are called, like this


```jl
function thru(data, functions)
    for f in functions
        data = f(data)
    end
    data
end

thru(10, [x->x+1, x->x*10, x -> x+300]) # 410
thru(10, []) # 10
```

so I'd expect it to behave the same as `thru(10, []) # 10`.

The other side of the coin is that 

```julia
@chain a begin 
A -> B
B -> C
C -> D
end
```

is a function that takes objects of type `A == typeof(a)`. If we don't have any functions in the block, then there's still an `A` object inside the function that we need to deal with. We can say it should pump that argument through, or it should swallow it the way that `function foo(x) end` does. 

I see it more like the sequence of functions.



> I wonder in what context this came up?

I was commenting out lines one at a time until I had an empty block. But it could also happen by generating the macro call programmatically.

**Comment by jkrumbiegel** [comment]
okay it seems like the one-argument-in-the-chain alternative syntax already returned that argument, so to make both syntax alternatives equivalent the other one also returns the input argument now https://github.com/jkrumbiegel/Chain.jl/commit/3810ae8f5b447c94a6b7bd9812f63b15e4c23d8a
