### ISSUE TITLE
.|> ?

### ISSUE THREAD

**Issue by ghost** [jkrumbiegel/Chain.jl#2]
What's the equivalent of `rand(100) .|> sin |> sum` ?

**Comment by jkrumbiegel** [comment]
There isn't a direct equivalent to that syntax. You can do:

```julia
@chain rand(100) begin
	sin.(_)
    sum
end
```

The problem is that writing only `sin.` is not possible, that gets parsed together with the next line as `sin.sum`. Another idea could be to enable `@.` syntax for standalone symbols, then one could possibly write:

```julia
@chain rand(100) begin
	@. sin
    sum
end
```

I'm not sure if that is more desirable than `sin.(_)`.

**Comment by jkrumbiegel** [comment]
Ok I've actually added that `@. symbol` special case now in case people prefer that in some situations. All other situations would just require using the normal `_` syntax, but I thought this was close enough to the single-symbol case to warrant a specific path.

**Comment by fredcallaway** [comment]
I think this will work in [v1.6](https://github.com/JuliaLang/julia/blob/v1.6.0-beta1/NEWS.md) (unless Chain.jl has to do something else to support the syntax)

```julia
@chain rand(100) begin
	.sin
    sum
end
```

**Comment by Oblynx** [comment]
> ```julia
> @chain rand(100) begin
> 	.sin
>     sum
> end
> ```

This doesn't work for me in v1.6.0 with Chain v0.4.6:
```julia
ERROR: LoadError: syntax: invalid identifier name "."
```

The `@.` syntax instead works fine, and even inline: `@chain rand(10) (@. sin) sum`

**Comment by fredcallaway** [comment]
~That sounds like a big in Chain.jl parsing then.~ According to the NEWS.md file I linked above:

> This means `.op` is functionally equivalent to `(x...) -> (op).(x...)`

So I think this issue should be reopened.

EDIT: on second thought, it should be a separate issue.
EDIT2: on third thought, I was confused.

**Comment by fredcallaway** [comment]
Apologies, I misunderstood the release notes. It only applies to operators, not functions. FWIW, it doesn't work with operators either, but I don't think the `.op` syntax would be very useful in this context (because few operators are unary)
