### ISSUE TITLE
Any syntax for `f()` evaluated with no arguments?

### ISSUE THREAD

**Issue by pdeffebach** [jkrumbiegel/Chain.jl#22]
Doesn't look like this is possible. 

Probably would only make sense at the beginning of a chain, right? So you would do 

```
@chain f() begin 
    ...
end
```

**Comment by jkrumbiegel** [comment]
What do you want to use this for? The premise is that you always want to chain your result in a `@chain` (otherwise use `@aside` which doesn't use implicit argument splicing for exactly that reason)

**Comment by pdeffebach** [comment]
yeah this is fine. Nothing actionable here.
