### ISSUE TITLE
Easier way to make anonymous functions

### ISSUE THREAD

**Issue by pdeffebach** [jkrumbiegel/Chain.jl#25]
I'm imagining somehtin like `@aside` but which takes in `_` and returns whatever the expression returns. 

```
@chain 1 begin 
    @anon begin 
        _ + 2 * 1000
     end
     mean()
end
```

I've been thinking of doing an `@anon` macro in DataFramesMeta, since the infrastructure is all there to do it with `Symbol`s. However this would need to be different, special-casing `_`.

**Comment by jkrumbiegel** [comment]
Can you give a more realistic example, what you wrote here works already without `@anon` around it

**Comment by pdeffebach** [comment]
Yeah, I'm thinking intermediate variables as well 

```
@chain 1 begin 
    @anon begin 
        x = 500 
        z = 78
        _ + x * z
    end
end
```

**Comment by jtrakk** [comment]
Is that the same as this?
```jl
@chain 1 begin 
    y-> begin 
        x = 500 
        z = 78
       y + x * z
    end
end
````

**Comment by pdeffebach** [comment]
hmmm yes it is. That's definitely easier. 

Though I guess that solution incurs a compilation cost that could be avoided if we let things happen in the normal scope. (This goes against my `@anon` name)

It also enables the user to leave the world of `_`, which complicates things.

**Comment by jkrumbiegel** [comment]
```julia 
@chain 1 begin 
    begin 
        x = 500 
        z = 78
        _ + x * z
    end
end
```

**Comment by pdeffebach** [comment]
Oh no kidding. I thought I tried that. Excellent!
