### ISSUE TITLE
@aside cuts the chain if the last statement

### ISSUE THREAD

**Issue by pfarndt** [jkrumbiegel/Chain.jl#32]
If `@aside` is the last last statement in a chain then it is cut. Consider:
```julia
using DataFrames, DataFramesMeta (v0.8.0)

df = @chain DataFrame(a = 1:4) begin
    @aside println(nrow(_))
end
```
This just prints out `4` and assigns `nothing `to `df`. This is unexpected  and unfortunate because one sometimes wants to know how many rows are left (or something similar) after some data crunching steps.

A possible (but unattractive) workaround is to place an `identity` in the last line:
```Julia
df = @chain DataFrame(a = 1:4) begin
    @aside println(nrow(_))
    identity
end
```
This now assigns `df` to be the expected 4 row `DataFrame`.

**Comment by jkrumbiegel** [comment]
Ah yeah I knew about this but didn't have time to fix it. I just need to repeat the last temp variable if the last statement is an `@aside` one

**Comment by jkrumbiegel** [comment]
fixed here https://github.com/jkrumbiegel/Chain.jl/commit/e89262bc59da8527c56e194b17d1ab7d913eeabd
