### ISSUE TITLE
allowing assignments to variables

### ISSUE THREAD

**Issue by pfarndt** [jkrumbiegel/Chain.jl#33]
It would be nice to allow assignments (intermediate or at the end) of a chain, such that code like this :

```julia
julia> using DataFramesMeta;

julia> df = DataFrame(a = [1, 2]);

julia> @chain df begin 
           @transform(y = :a)
           newdata = _
       end;

julia> newdata
ERROR: UndefVarError: newdata not defined
```
would work. This could also be very helpful for "debugging".

 (@pdeffebach, see also [here](https://github.com/JuliaData/DataFramesMeta.jl/issues/232#issue-824996695))

**Comment by jkrumbiegel** [comment]
That actually works these days, just forgot to close the issue:

```julia
julia> @chain begin
           [1, 2, 3]
           sum
           d = _
       end
6

julia> d
6
```

**Comment by pfarndt** [comment]
Thanks!
