### ISSUE TITLE
Potential incompatibility with Julia LSP?

### ISSUE THREAD

**Issue by max-sixty** [jkrumbiegel/Chain.jl#40]
This is another one "I'm not sure where the bug lies" — I hope these are helpful regardless — please feel free to close if it's not an issue with this library.

It seems that Julia LSP misunderstands `@chain` with a user function. Here's an example:

```julia
using Chain, Underscores, StatsBase, Base.Iterators, DataStructures

input = @chain begin
    read(open("Day-6.txt"), String)
    strip
    split(",")
    @. parse(Int, _)
end

start = @chain input countmap DefaultDict(0, _)

function run(start, n)
    current = copy(start)
    for i = 1:n
        next = DefaultDict(0, Dict(i - 1 => current[i] for i in keys(current) if i > 0))
        next[6] += next[8] = current[0]
        current = next
    end
    current
end

@chain start run(256) values sum  # run returns "Possible method call error"
```

Here's a screenshot:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/5635139/144913084-909c465c-ac19-43c7-bf42-177eef550f01.png">

**Comment by jkrumbiegel** [comment]
I think there's nothing I can do about that, the LSP is just not smart enough to pre-expand the macro before checking for method signature matches.

**Comment by max-sixty** [comment]
Thanks @jkrumbiegel . I can put an issue in there if you think that's reasonable...
