### ISSUE TITLE
Allow no begin and end block for single row chaining

### ISSUE THREAD

**Issue by xiaodaigh** [jkrumbiegel/Chain.jl#5]
`@chain df some_function`

Allow this syntax where there is only one line

**Comment by jkrumbiegel** [comment]
I could in theory add that, although I find that usually these sorts of chains are pretty hard to read. Or is it too opinionated not to allow that syntax?

Maybe you could give a more "real world" example that you need. `@chain df some_function` is normally going to be written as `some_function(df)` of course

**Comment by xiaodaigh** [comment]
No worries. Not important
