### ISSUE TITLE
Use first item of chain block as input

### ISSUE THREAD

**Issue by swt30** [jkrumbiegel/Chain.jl#8]
Just a thought that it might look a little neater if the first item of the chain block could be taken as the input to the chain, in the case where no input is supplied.

This is useful where you're assigning the result of the block to a variable, and have a long function call or variable name as the input.

Compare:
```jl
some_output_variable_name = @chain some_long_variable_name begin
    do_something()
	do_something_else(parameter)
    do_other_thing(parameter, _)
end
```

```jl
some_output_variable_name = @chain begin
    some_long_variable_name
    do_something()
	do_something_else(parameter)
    do_other_thing(parameter, _)
end
```

**Comment by jkrumbiegel** [comment]
I thought about this as well, maybe it's a good idea. I wasn't sure at first if it's weird that then one line is different from the others, but maybe it's so obvious that it's not a problem

**Comment by jkrumbiegel** [comment]
added this in 0.4.1

**Comment by swt30** [comment]
Thanks, been using it with this change and it's really nice :)
